version: '2'

volumes:
  nextcloud:
  nextcloud_db:

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_PASSWORD=ED87KsDboPpIXmSMl9jwDEGE
      - MYSQL_ROOT_PASSWORD=HxQnzNycCv9vZYqtz2BfBJRB
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=ED87KsDboPpIXmSMl9jwDEGE
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
